MONGODB_HOST: mongodb-{{ env }}.daws86s.cfd
REDIS_HOST: redis-{{ env }}.daws86s.cfd
CATALOGUE_HOST: catalogue-{{ env }}.daws86s.cfd
CART_HOST: cart-{{ env }}.daws86s.cfd
MYSQL_HOST: mysql-{{ env }}.daws86s.cfd
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86s.cfd
USER_HOST: user-{{ env }}.daws86s.cfd
SHIPPING_HOST: shipping-{{ env }}.daws86s.cfd
PAYMENT_HOST: payment-{{ env }}.daws86s.cfd